### ISSUE TITLE
lein repl returns error

### ISSUE THREAD

**Issue by oxlsf** [wit-ai/duckling#68]
git clone https://github.com/wit-ai/duckling
    cd duckling
    lein repl

    Exception in thread "main" java.lang.IllegalArgumentException: No value supplied for key: [:init-ns duckling.core] (NO_SOURCE_FILE:0)
	    at clojure.lang.Compiler.eval(Compiler.java:5441)
	    at clojure.lang.Compiler.eval(Compiler.java:5392)
	    at clojure.core$eval.invoke(core.clj:2382)
	    at clojure.main$eval_opt.invoke(main.clj:235)
	    at clojure.main$initialize.invoke(main.clj:254)
	    at clojure.main$script_opt.invoke(main.clj:270)
 	    at clojure.main$main.doInvoke(main.clj:354)
	    at clojure.lang.RestFn.invoke(RestFn.java:457)
	    at clojure.lang.Var.invoke(Var.java:377)
	    at clojure.lang.AFn.applyToHelper(AFn.java:172)
	    at clojure.lang.Var.applyTo(Var.java:482)
	    at clojure.main.main(main.java:37)
    Caused by: java.lang.IllegalArgumentException: No value supplied for key: [:init-ns duckling.core]
	    at clojure.lang.PersistentHashMap.createWithCheck(PersistentHashMap.java:89)
	    at clojure.core$hash_map.doInvoke(core.clj:327)
	    at clojure.lang.RestFn.applyTo(RestFn.java:137)
	    at clojure.core$apply.invoke(core.clj:540)
	    at leiningen.repl$repl_options.invoke(repl.clj:16)
	    at leiningen.repl$repl_server.doInvoke(repl.clj:69)
	    at clojure.lang.RestFn.applyTo(RestFn.java:146)
	    at clojure.core$apply.invoke(core.clj:546)
	    at leiningen.repl$repl.invoke(repl.clj:145)
	    at clojure.lang.Var.invoke(Var.java:365)
	    at clojure.lang.AFn.applyToHelper(AFn.java:161)
	    at clojure.lang.Var.applyTo(Var.java:482)
	    at clojure.core$apply.invoke(core.clj:542)
	    at leiningen.core$apply_task.invoke(core.clj:262)
	    at leiningen.core$_main.doInvoke(core.clj:329)
	    at clojure.lang.RestFn.invoke(RestFn.java:410)
	    at clojure.lang.AFn.applyToHelper(AFn.java:161)
	    at clojure.lang.RestFn.applyTo(RestFn.java:132)
	    at clojure.core$apply.invoke(core.clj:542)
	    at leiningen.core$_main.invoke(core.clj:332)
	    at user$eval73.invoke(NO_SOURCE_FILE:1)
	    at clojure.lang.Compiler.eval(Compiler.java:5425)
	    ... 11 more

**Comment by l5t** [comment]
Just tried and it works for me (Clojure 1.6.0). Can you check your version of Clojure?
